[package]
name = "tantivy-recover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tantivy = {version="0.19.1",features = ["brotli-compression"]}
tqdm = "0.4.3"
csv = "1.1"