[package]
name = "tantivy-recover"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tantivy = {version="0.21"}
tqdm = "0.4.3"
csv = "1.1"